### ISSUE TITLE
Make this a CocoaPod

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/RSParser#20]

**Comment by kingmatusevich** [comment]
+1

**Comment by dcilia** [comment]
Can we also add ```carthage``` & ```swift package manager``` support?

**Comment by MartinW** [comment]
It appears that `pod install` fails to include .swift files? RSParser folder in Pods has no Swift files. Project compiles but `FeedParser.parse(parserData)` gives error `Type 'FeedParser' has no member 'parse'`.

**Comment by dcilia** [comment]
@MartinW good catch, turns out the Podspec has an extra space between h/m and swift ->  ```{h,m, swift} ``` .  Removing the space fixes the issue.  I'll make a quick PR, can you try and test it?

Should be:

``` {h,m,swift} ``` not ```{h,m, swift}```

**Comment by dcilia** [comment]
Tested it locally, seems to show all the swift files.

**Comment by MartinW** [comment]
Has the Podspec been updated in CocoaPods/Specs?
