### ISSUE TITLE
There is also an Atom-In-JSON format in the wild

### ISSUE THREAD

**Issue by dfawcus** [brentsimmons/RSParser#59]
Blogger also offers an alternate feed format, being essentially a google data JSON (https://developers.google.com/gdata/docs/json) rendition of the feed.

So one has these options for blogger feeds, not all feeds offering all possibilities:

default:   http://blogname.blogspot.com/feeds/posts/default
Atom:   http://blogname.blogspot.com/feeds/posts/default?alt=atom
 RSS:    http://blogname.blogspot.com/feeds/posts/default?alt=rss
 RDF:    http://blogname.blogspot.com/feeds/posts/default?alt=rdf
JSON:   http://blogname.blogspot.com/feeds/posts/default?alt=json

Do you also wish to support that extra format?

**Comment by brentsimmons** [comment]
I don’t think so — as long as Blogger blogs are offering something we already support, we don’t need to support this format too.
