### ISSUE TITLE
Linux support for use in server-side

### ISSUE THREAD

**Issue by JS1010111** [brentsimmons/RSParser#62]
Is it supposed to work with SPM on Linux? I confess that I did not tried yet.

**Comment by brentsimmons** [comment]
There’s a bunch of Objective-C code in here. I highly doubt RSParser could be made to work on Linux without a whole bunch of rewriting.

**Comment by JS1010111** [comment]
Oh sure... I completely ignored this fact. Thanks for answering anyway!
